# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
    ]
